/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Failure: typeof import('./src/components/Failure.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    ProjectsLayout: typeof import('./src/components/layouts/ProjectsLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningTask: typeof import('./src/components/project/RunningTask.vue')['default']
  }
}
